services:
  node:
    build: .
    command: npm run dev
    ports:
      - 3000:4000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - .:/usr/app
    environment:
      - DB_HOST=db
    
  admin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mysql:lts
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./db-data:/var/lib/mysql
